INSERT INTO USER (EMAIL, PASSWORD) VALUES('diogof.fabrile@gmail.com', '123');
INSERT INTO USER (EMAIL, PASSWORD) VALUES('user2@gmail.com', '123');
INSERT INTO USER (EMAIL, PASSWORD) VALUES('user3@gmail.com', '123');
INSERT INTO USER (EMAIL, PASSWORD) VALUES('user4@gmail.com', '123');
INSERT INTO USER (EMAIL, PASSWORD) VALUES('user5@gmail.com', '123');
INSERT INTO USER (EMAIL, PASSWORD) VALUES('user6@gmail.com', '123');